#pragma once

#include "mips/mips.hpp"
#include "types.hpp"

namespace ee {
template<mips::CpuImpl> void add(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void addi(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void addiu(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void addu(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void and_(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void andi(u32 rs, u32 rt, u16 imm);
template<mips::CpuImpl> void beq(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void beql(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void bgez(u32 rs, s16 imm);
template<mips::CpuImpl> void bgezal(u32 rs, s16 imm);
template<mips::CpuImpl> void bgezall(u32 rs, s16 imm);
template<mips::CpuImpl> void bgezl(u32 rs, s16 imm);
template<mips::CpuImpl> void bgtz(u32 rs, s16 imm);
template<mips::CpuImpl> void bgtzl(u32 rs, s16 imm);
template<mips::CpuImpl> void blez(u32 rs, s16 imm);
template<mips::CpuImpl> void blezl(u32 rs, s16 imm);
template<mips::CpuImpl> void bltz(u32 rs, s16 imm);
template<mips::CpuImpl> void bltzal(u32 rs, s16 imm);
template<mips::CpuImpl> void bltzall(u32 rs, s16 imm);
template<mips::CpuImpl> void bltzl(u32 rs, s16 imm);
template<mips::CpuImpl> void bne(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void bnel(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void break_();
template<mips::CpuImpl> void cache();
template<mips::CpuImpl> void dadd(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void daddi(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void daddiu(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void daddu(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void div(u32 rs, u32 rt);
template<mips::CpuImpl> void div1(u32 rs, u32 rt);
template<mips::CpuImpl> void divu(u32 rs, u32 rt);
template<mips::CpuImpl> void divu1(u32 rs, u32 rt);
template<mips::CpuImpl> void dsll(u32 rt, u32 rd, u32 sa);
template<mips::CpuImpl> void dsll32(u32 rt, u32 rd, u32 sa);
template<mips::CpuImpl> void dsllv(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void dsra(u32 rt, u32 rd, u32 sa);
template<mips::CpuImpl> void dsra32(u32 rt, u32 rd, u32 sa);
template<mips::CpuImpl> void dsrav(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void dsrl(u32 rt, u32 rd, u32 sa);
template<mips::CpuImpl> void dsrl32(u32 rt, u32 rd, u32 sa);
template<mips::CpuImpl> void dsrlv(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void dsub(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void dsubu(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void j(u32 imm26);
template<mips::CpuImpl> void jal(u32 imm26);
template<mips::CpuImpl> void jalr(u32 rs, u32 rd);
template<mips::CpuImpl> void jr(u32 rs);
template<mips::CpuImpl> void lb(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void lbu(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void ld(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void ldl(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void ldr(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void lh(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void lhu(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void lq(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void lui(u32 rt, s16 imm);
template<mips::CpuImpl> void lw(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void lwl(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void lwr(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void lwu(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void mfhi(u32 rd);
template<mips::CpuImpl> void mfhi1(u32 rd);
template<mips::CpuImpl> void mflo(u32 rd);
template<mips::CpuImpl> void mflo1(u32 rd);
template<mips::CpuImpl> void mfsa(u32 rd);
template<mips::CpuImpl> void movn(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void movz(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void mthi(u32 rs);
template<mips::CpuImpl> void mthi1(u32 rs);
template<mips::CpuImpl> void mtlo(u32 rs);
template<mips::CpuImpl> void mtlo1(u32 rs);
template<mips::CpuImpl> void mtsa(u32 rs);
template<mips::CpuImpl> void mtsab(u32 rs, s16 imm);
template<mips::CpuImpl> void mtsah(u32 rs, s16 imm);
template<mips::CpuImpl> void mult(u32 rs, u32 rt);
template<mips::CpuImpl> void mult1(u32 rs, u32 rt);
template<mips::CpuImpl> void multu(u32 rs, u32 rt);
template<mips::CpuImpl> void multu1(u32 rs, u32 rt);
template<mips::CpuImpl> void nor(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void or_(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void ori(u32 rs, u32 rt, u16 imm);
template<mips::CpuImpl> void pref();
template<mips::CpuImpl> void sb(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void sd(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void sdl(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void sdr(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void sh(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void sll(u32 rt, u32 rd, u32 sa);
template<mips::CpuImpl> void sllv(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void slt(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void slti(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void sltiu(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void sltu(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void sq(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void sra(u32 rt, u32 rd, u32 sa);
template<mips::CpuImpl> void srav(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void srl(u32 rt, u32 rd, u32 sa);
template<mips::CpuImpl> void srlv(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void sub(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void subu(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void sw(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void swl(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void swr(u32 rs, u32 rt, s16 imm);
template<mips::CpuImpl> void sync();
template<mips::CpuImpl> void syscall();
template<mips::CpuImpl> void teq(u32 rs, u32 rt);
template<mips::CpuImpl> void teqi(u32 rs, s16 imm);
template<mips::CpuImpl> void tge(u32 rs, u32 rt);
template<mips::CpuImpl> void tgei(u32 rs, s16 imm);
template<mips::CpuImpl> void tgeu(u32 rs, u32 rt);
template<mips::CpuImpl> void tgeiu(u32 rs, s16 imm);
template<mips::CpuImpl> void tlt(u32 rs, u32 rt);
template<mips::CpuImpl> void tlti(u32 rs, s16 imm);
template<mips::CpuImpl> void tltu(u32 rs, u32 rt);
template<mips::CpuImpl> void tltiu(u32 rs, s16 imm);
template<mips::CpuImpl> void tne(u32 rs, u32 rt);
template<mips::CpuImpl> void tnei(u32 rs, s16 imm);
template<mips::CpuImpl> void xor_(u32 rs, u32 rt, u32 rd);
template<mips::CpuImpl> void xori(u32 rs, u32 rt, u16 imm);
} // namespace ee
